# Generated by Django 4.2.7 on 2023-12-11 06:49

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('contacts', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='contact',
            old_name='address',
            new_name='notes',
        ),
        migrations.AddField(
            model_name='contact',
            name='time',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
    ]
